---
abstract: 'simple DBI plugin for Mojolicious.'
author:
  - 'Konstantin Kapitanov <perlovik@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.102160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-DBI
requires:
  DBI: 0
  Mojo: 0.999910
version: 0.03
